#
# Travis CI config file
#

language: python

python:
  - "2.7"
  - "3.4"
  - "3.6"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"


# install chainmap to support python 2
before_install:
  - if [ "$TRAVIS_PYTHON_VERSION" == "2.7" ]; then pip install chainmap; fi


# command to run tests
script:
  - PYTHONPATH=. pytest

