name: 'tests-ci'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "13 20 * * 3"

jobs:
  tests-ci:

    strategy:
      fail-fast: true
      matrix:
        python-version:
          - "2.7"
          - "3.4"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
        os:
          - 'ubuntu-latest'

    runs-on: '${{ matrix.os }}'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '${{ matrix.python-version }}'

      - name: 'Install dependencies'
        run: |-
          pip install pytest; if [ "${{ matrix.python-version }}" == "2.7" ]; then pip install chainmap; fi

      - name: 'Run tests'
        run: pytest
